kiosk_mode:
  hide_header: false
  hide_sidebar: true
  hide_menubutton: true
  hide_overflow: true
  user_settings:
    - users:
        - kairoshub
        - utente
        - user
      hide_header: false
      hide_sidebar: true
      hide_menubutton: true
      hide_overflow: true

button_card_templates: !include hakairos-configuration/frontend/components/button_card_templates.yaml

views:
  - title: HOME
    path: home
    panel: true
    show_name: true
    style: |
          #view {
            padding-left: 1% !important;
            padding-right: 1% !important;
          }
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/components/theme/header.yaml        
          - type: 'custom:button-card'
            template: row_space_10
          - type: horizontal-stack
            cards:
              - !include hakairos-configuration/frontend/components/theme/body_col_1.yaml
              - !include hakairos-configuration/frontend/components/theme/body_col_3.yaml        
  - title: CLIMA
    path: clima
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima.yaml
  - title: ASSISTENZA
    icon: 
    path: assistenza
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/assistance.yaml
  - title: Programma 1
    path: clima-p1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/p1.yaml
  - path: clima-p1-1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/p1-1.yaml
  - path: clima-p1-2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/p1-2.yaml
  - path: clima-p1-3
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/p1-3.yaml
  - path: clima-p1-4
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/p1-4.yaml
  - path: clima-p1-5
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/p1-5.yaml
  - path: clima-p1-6
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/p1-6.yaml
  - path: clima-p1-7
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/p1-7.yaml